services:
  nginx:
    image: 'nginx:latest'
    volumes:
      - './:/var/www'
      - './_docker/nginx/conf.d:/etc/nginx/conf.d'
    ports:
      - '80:80'
    depends_on:
      - 'app'
    container_name: 'project_nginx'
  app:
    build:
      context: '.'
      dockerfile: '_docker/app/Dockerfile'
    volumes:
      - './:/var/www'
    container_name: 'project_app'
    depends_on:
      - mysql

  mysql:
    image: 'mysql:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - './tmp/db:/var/lib/mysql'
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: project_db

